/**
 * [infrastructure-configuration]
 */

 
const FRONTEND_DOMAIN = process.env.FRONTEND_DOMAIN
const FRONTEND_PATH_REGISTRATION = process.env.FRONTEND_PATH_REGISTRATION
const FRONTEND_PATH_RECOVER_BY_CODE = process.env.FRONTEND_PATH_RECOVER_BY_CODE
const FRONTEND_PATH_RECOVER_BY_PASSWORD = process.env.FRONTEND_PATH_RECOVER_BY_PASSWORD

module.exports = {
  domain: process.env.FRONTEND_DOMAIN,
  registrationUrl: `${FRONTEND_DOMAIN}${FRONTEND_PATH_REGISTRATION}`,
  verifyCodeUrl: `${FRONTEND_DOMAIN}${FRONTEND_PATH_RECOVER_BY_CODE}`,
  verifyByResetPasswordUrl: `${FRONTEND_DOMAIN}${FRONTEND_PATH_RECOVER_BY_PASSWORD}`,
}
